-- Comprehensive skills seed data (150+ skills)
-- Run this in your Neon SQL editor

INSERT INTO skills (slug, display_name, category, match_languages, match_topics, match_keywords) VALUES
  ('typescript', 'TypeScript', 'language', ARRAY['TypeScript']::TEXT[], ARRAY['typescript', 'ts']::TEXT[], ARRAY['typescript', '.ts', '.tsx']::TEXT[]),
  ('javascript', 'JavaScript', 'language', ARRAY['JavaScript']::TEXT[], ARRAY['javascript', 'js', 'nodejs', 'node', 'ecmascript']::TEXT[], ARRAY['javascript', '.js', '.jsx', 'ecmascript']::TEXT[]),
  ('python', 'Python', 'language', ARRAY['Python']::TEXT[], ARRAY['python', 'python3', 'py', 'django', 'flask', 'fastapi']::TEXT[], ARRAY['python', '.py']::TEXT[]),
  ('go', 'Go', 'language', ARRAY['Go']::TEXT[], ARRAY['golang', 'go']::TEXT[], ARRAY['golang', '.go']::TEXT[]),
  ('rust', 'Rust', 'language', ARRAY['Rust']::TEXT[], ARRAY['rust', 'rustlang', 'cargo']::TEXT[], ARRAY['rust', '.rs', 'cargo']::TEXT[]),
  ('java', 'Java', 'language', ARRAY['Java']::TEXT[], ARRAY['java', 'jvm', 'spring', 'spring-boot', 'maven', 'gradle']::TEXT[], ARRAY['java', '.java', 'spring-boot']::TEXT[]),
  ('kotlin', 'Kotlin', 'language', ARRAY['Kotlin']::TEXT[], ARRAY['kotlin', 'android-kotlin', 'kotlin-multiplatform', 'kmm', 'kmp']::TEXT[], ARRAY['kotlin', '.kt', '.kts']::TEXT[]),
  ('swift', 'Swift', 'language', ARRAY['Swift']::TEXT[], ARRAY['swift', 'swiftui', 'ios-swift', 'swift-package-manager']::TEXT[], ARRAY['swift', '.swift', 'swiftui']::TEXT[]),
  ('cpp', 'C++', 'language', ARRAY['C++']::TEXT[], ARRAY['cpp', 'cplusplus', 'c-plus-plus']::TEXT[], ARRAY['c++', '.cpp', '.hpp', '.cc', '.cxx']::TEXT[]),
  ('c', 'C', 'language', ARRAY['C']::TEXT[], ARRAY['c-programming', 'clang', 'c-language']::TEXT[], ARRAY['.c', '.h']::TEXT[]),
  ('csharp', 'C#', 'language', ARRAY['C#']::TEXT[], ARRAY['csharp', 'dotnet', 'dotnet-core', 'aspnet', 'unity']::TEXT[], ARRAY['csharp', '.cs', 'dotnet', '.net']::TEXT[]),
  ('php', 'PHP', 'language', ARRAY['PHP']::TEXT[], ARRAY['php', 'laravel', 'symfony', 'wordpress', 'composer']::TEXT[], ARRAY['php', '.php', 'laravel', 'symfony']::TEXT[]),
  ('ruby', 'Ruby', 'language', ARRAY['Ruby']::TEXT[], ARRAY['ruby', 'rails', 'ruby-on-rails', 'rubygems', 'sinatra']::TEXT[], ARRAY['ruby', '.rb', 'rails']::TEXT[]),
  ('scala', 'Scala', 'language', ARRAY['Scala']::TEXT[], ARRAY['scala', 'akka', 'play-framework', 'sbt']::TEXT[], ARRAY['scala', '.scala']::TEXT[]),
  ('elixir', 'Elixir', 'language', ARRAY['Elixir']::TEXT[], ARRAY['elixir', 'phoenix', 'erlang', 'otp']::TEXT[], ARRAY['elixir', '.ex', '.exs', 'phoenix']::TEXT[]),
  ('haskell', 'Haskell', 'language', ARRAY['Haskell']::TEXT[], ARRAY['haskell', 'functional-programming', 'ghc']::TEXT[], ARRAY['haskell', '.hs']::TEXT[]),
  ('clojure', 'Clojure', 'language', ARRAY['Clojure']::TEXT[], ARRAY['clojure', 'clojurescript', 'leiningen']::TEXT[], ARRAY['clojure', '.clj', '.cljs']::TEXT[]),
  ('r', 'R', 'language', ARRAY['R']::TEXT[], ARRAY['r', 'rstats', 'r-programming', 'tidyverse', 'ggplot2', 'shiny']::TEXT[], ARRAY['.r', 'rstats']::TEXT[]),
  ('julia', 'Julia', 'language', ARRAY['Julia']::TEXT[], ARRAY['julia', 'julialang', 'scientific-computing']::TEXT[], ARRAY['julia', '.jl']::TEXT[]),
  ('dart', 'Dart', 'language', ARRAY['Dart']::TEXT[], ARRAY['dart', 'flutter', 'dartlang']::TEXT[], ARRAY['dart', '.dart']::TEXT[]),
  ('lua', 'Lua', 'language', ARRAY['Lua']::TEXT[], ARRAY['lua', 'luajit', 'neovim', 'roblox']::TEXT[], ARRAY['lua', '.lua']::TEXT[]),
  ('perl', 'Perl', 'language', ARRAY['Perl']::TEXT[], ARRAY['perl', 'perl5', 'perl6', 'raku']::TEXT[], ARRAY['perl', '.pl', '.pm']::TEXT[]),
  ('shell', 'Shell/Bash', 'language', ARRAY['Shell', 'Bash']::TEXT[], ARRAY['shell', 'bash', 'zsh', 'shell-script', 'scripting']::TEXT[], ARRAY['.sh', 'bash', 'shell']::TEXT[]),
  ('powershell', 'PowerShell', 'language', ARRAY['PowerShell']::TEXT[], ARRAY['powershell', 'pwsh', 'windows-automation']::TEXT[], ARRAY['powershell', '.ps1']::TEXT[]),
  ('objective-c', 'Objective-C', 'language', ARRAY['Objective-C']::TEXT[], ARRAY['objective-c', 'objc', 'ios-objc']::TEXT[], ARRAY['objective-c', '.m', '.mm']::TEXT[]),
  ('zig', 'Zig', 'language', ARRAY['Zig']::TEXT[], ARRAY['zig', 'ziglang']::TEXT[], ARRAY['zig', '.zig']::TEXT[]),
  ('nim', 'Nim', 'language', ARRAY['Nim']::TEXT[], ARRAY['nim', 'nimlang']::TEXT[], ARRAY['nim', '.nim']::TEXT[]),
  ('ocaml', 'OCaml', 'language', ARRAY['OCaml']::TEXT[], ARRAY['ocaml', 'reason', 'reasonml']::TEXT[], ARRAY['ocaml', '.ml', '.mli']::TEXT[]),
  ('fsharp', 'F#', 'language', ARRAY['F#']::TEXT[], ARRAY['fsharp', 'dotnet-fsharp']::TEXT[], ARRAY['fsharp', '.fs', '.fsx']::TEXT[]),
  ('solidity', 'Solidity', 'language', ARRAY['Solidity']::TEXT[], ARRAY['solidity', 'smart-contracts', 'ethereum', 'evm']::TEXT[], ARRAY['solidity', '.sol']::TEXT[]),
  ('vyper', 'Vyper', 'language', ARRAY['Vyper']::TEXT[], ARRAY['vyper', 'ethereum-vyper']::TEXT[], ARRAY['vyper', '.vy']::TEXT[]),
  ('move', 'Move', 'language', ARRAY['Move']::TEXT[], ARRAY['move', 'aptos', 'sui', 'move-language']::TEXT[], ARRAY['move', '.move']::TEXT[]),
  ('cairo', 'Cairo', 'language', ARRAY['Cairo']::TEXT[], ARRAY['cairo', 'starknet', 'starkware']::TEXT[], ARRAY['cairo', '.cairo']::TEXT[]),
  ('wasm', 'WebAssembly', 'language', ARRAY['WebAssembly']::TEXT[], ARRAY['webassembly', 'wasm', 'wasi', 'emscripten']::TEXT[], ARRAY['wasm', 'webassembly', '.wasm']::TEXT[]),
  ('cobol', 'COBOL', 'language', ARRAY['COBOL']::TEXT[], ARRAY['cobol', 'mainframe']::TEXT[], ARRAY['cobol', '.cob', '.cbl']::TEXT[]),
  ('fortran', 'Fortran', 'language', ARRAY['Fortran']::TEXT[], ARRAY['fortran', 'scientific-computing', 'hpc']::TEXT[], ARRAY['fortran', '.f90', '.f95']::TEXT[]),
  ('v', 'V', 'language', ARRAY['V']::TEXT[], ARRAY['vlang', 'v-language']::TEXT[], ARRAY['vlang', '.v']::TEXT[]),
  ('crystal', 'Crystal', 'language', ARRAY['Crystal']::TEXT[], ARRAY['crystal', 'crystal-lang']::TEXT[], ARRAY['crystal', '.cr']::TEXT[]),
  ('groovy', 'Groovy', 'language', ARRAY['Groovy']::TEXT[], ARRAY['groovy', 'gradle', 'grails']::TEXT[], ARRAY['groovy', '.groovy']::TEXT[]),
  ('erlang', 'Erlang', 'language', ARRAY['Erlang']::TEXT[], ARRAY['erlang', 'otp', 'beam']::TEXT[], ARRAY['erlang', '.erl']::TEXT[]),
  ('react', 'React', 'framework', ARRAY[]::TEXT[], ARRAY['react', 'reactjs', 'react-hooks', 'react-router', 'redux']::TEXT[], ARRAY['react', 'jsx', 'tsx']::TEXT[]),
  ('nextjs', 'Next.js', 'framework', ARRAY[]::TEXT[], ARRAY['nextjs', 'next-js', 'next', 'vercel']::TEXT[], ARRAY['next.js', 'nextjs']::TEXT[]),
  ('vue', 'Vue', 'framework', ARRAY['Vue']::TEXT[], ARRAY['vue', 'vuejs', 'vue3', 'vuex', 'pinia', 'nuxt']::TEXT[], ARRAY['vue', '.vue', 'vuejs']::TEXT[]),
  ('nuxt', 'Nuxt', 'framework', ARRAY[]::TEXT[], ARRAY['nuxt', 'nuxtjs', 'nuxt3']::TEXT[], ARRAY['nuxt', 'nuxtjs']::TEXT[]),
  ('angular', 'Angular', 'framework', ARRAY[]::TEXT[], ARRAY['angular', 'angularjs', 'angular2', 'ngrx', 'rxjs']::TEXT[], ARRAY['angular']::TEXT[]),
  ('svelte', 'Svelte', 'framework', ARRAY['Svelte']::TEXT[], ARRAY['svelte', 'sveltekit', 'svelte-kit']::TEXT[], ARRAY['svelte', '.svelte']::TEXT[]),
  ('solid', 'SolidJS', 'framework', ARRAY[]::TEXT[], ARRAY['solidjs', 'solid-js', 'solid-start']::TEXT[], ARRAY['solidjs', 'solid-js']::TEXT[]),
  ('astro', 'Astro', 'framework', ARRAY['Astro']::TEXT[], ARRAY['astro', 'astro-js', 'astrojs']::TEXT[], ARRAY['astro', '.astro']::TEXT[]),
  ('remix', 'Remix', 'framework', ARRAY[]::TEXT[], ARRAY['remix', 'remix-run']::TEXT[], ARRAY['remix']::TEXT[]),
  ('qwik', 'Qwik', 'framework', ARRAY[]::TEXT[], ARRAY['qwik', 'qwik-city']::TEXT[], ARRAY['qwik']::TEXT[]),
  ('htmx', 'HTMX', 'framework', ARRAY[]::TEXT[], ARRAY['htmx', 'hypermedia']::TEXT[], ARRAY['htmx']::TEXT[]),
  ('alpine', 'Alpine.js', 'framework', ARRAY[]::TEXT[], ARRAY['alpinejs', 'alpine-js']::TEXT[], ARRAY['alpinejs', 'alpine.js']::TEXT[]),
  ('ember', 'Ember.js', 'framework', ARRAY[]::TEXT[], ARRAY['ember', 'emberjs', 'ember-cli']::TEXT[], ARRAY['ember', 'emberjs']::TEXT[]),
  ('preact', 'Preact', 'framework', ARRAY[]::TEXT[], ARRAY['preact', 'preactjs']::TEXT[], ARRAY['preact']::TEXT[]),
  ('django', 'Django', 'framework', ARRAY[]::TEXT[], ARRAY['django', 'django-rest-framework', 'drf', 'django-ninja']::TEXT[], ARRAY['django']::TEXT[]),
  ('fastapi', 'FastAPI', 'framework', ARRAY[]::TEXT[], ARRAY['fastapi', 'starlette']::TEXT[], ARRAY['fastapi']::TEXT[]),
  ('flask', 'Flask', 'framework', ARRAY[]::TEXT[], ARRAY['flask', 'flask-restful']::TEXT[], ARRAY['flask']::TEXT[]),
  ('express', 'Express.js', 'framework', ARRAY[]::TEXT[], ARRAY['express', 'expressjs', 'express-js']::TEXT[], ARRAY['express', 'expressjs']::TEXT[]),
  ('nestjs', 'NestJS', 'framework', ARRAY[]::TEXT[], ARRAY['nestjs', 'nest-js']::TEXT[], ARRAY['nestjs', 'nest.js']::TEXT[]),
  ('fastify', 'Fastify', 'framework', ARRAY[]::TEXT[], ARRAY['fastify']::TEXT[], ARRAY['fastify']::TEXT[]),
  ('hono', 'Hono', 'framework', ARRAY[]::TEXT[], ARRAY['hono', 'honojs']::TEXT[], ARRAY['hono']::TEXT[]),
  ('spring', 'Spring', 'framework', ARRAY[]::TEXT[], ARRAY['spring', 'spring-boot', 'spring-framework', 'spring-cloud']::TEXT[], ARRAY['spring', 'spring-boot']::TEXT[]),
  ('rails', 'Ruby on Rails', 'framework', ARRAY[]::TEXT[], ARRAY['rails', 'ruby-on-rails', 'rubyonrails']::TEXT[], ARRAY['rails', 'rubyonrails']::TEXT[]),
  ('laravel', 'Laravel', 'framework', ARRAY[]::TEXT[], ARRAY['laravel', 'laravel-framework', 'lumen']::TEXT[], ARRAY['laravel']::TEXT[]),
  ('symfony', 'Symfony', 'framework', ARRAY[]::TEXT[], ARRAY['symfony', 'symfony-framework']::TEXT[], ARRAY['symfony']::TEXT[]),
  ('gin', 'Gin', 'framework', ARRAY[]::TEXT[], ARRAY['gin', 'gin-gonic']::TEXT[], ARRAY['gin-gonic', 'gin']::TEXT[]),
  ('fiber', 'Fiber', 'framework', ARRAY[]::TEXT[], ARRAY['fiber', 'gofiber']::TEXT[], ARRAY['fiber', 'gofiber']::TEXT[]),
  ('echo', 'Echo', 'framework', ARRAY[]::TEXT[], ARRAY['echo', 'labstack-echo']::TEXT[], ARRAY['echo', 'labstack']::TEXT[]),
  ('actix', 'Actix', 'framework', ARRAY[]::TEXT[], ARRAY['actix', 'actix-web']::TEXT[], ARRAY['actix', 'actix-web']::TEXT[]),
  ('axum', 'Axum', 'framework', ARRAY[]::TEXT[], ARRAY['axum', 'tokio']::TEXT[], ARRAY['axum']::TEXT[]),
  ('rocket', 'Rocket', 'framework', ARRAY[]::TEXT[], ARRAY['rocket', 'rocket-rs']::TEXT[], ARRAY['rocket']::TEXT[]),
  ('phoenix', 'Phoenix', 'framework', ARRAY[]::TEXT[], ARRAY['phoenix', 'phoenix-framework', 'phoenix-liveview']::TEXT[], ARRAY['phoenix']::TEXT[]),
  ('aspnet', 'ASP.NET', 'framework', ARRAY[]::TEXT[], ARRAY['aspnet', 'aspnetcore', 'asp-net-core', 'blazor']::TEXT[], ARRAY['aspnet', 'asp.net', 'blazor']::TEXT[]),
  ('react-native', 'React Native', 'framework', ARRAY[]::TEXT[], ARRAY['react-native', 'reactnative', 'expo']::TEXT[], ARRAY['react-native', 'expo']::TEXT[]),
  ('flutter', 'Flutter', 'framework', ARRAY[]::TEXT[], ARRAY['flutter', 'flutter-apps', 'flutterdev']::TEXT[], ARRAY['flutter']::TEXT[]),
  ('ionic', 'Ionic', 'framework', ARRAY[]::TEXT[], ARRAY['ionic', 'ionic-framework', 'capacitor']::TEXT[], ARRAY['ionic', 'capacitor']::TEXT[]),
  ('swiftui', 'SwiftUI', 'framework', ARRAY[]::TEXT[], ARRAY['swiftui', 'swift-ui']::TEXT[], ARRAY['swiftui']::TEXT[]),
  ('jetpack-compose', 'Jetpack Compose', 'framework', ARRAY[]::TEXT[], ARRAY['jetpack-compose', 'compose', 'android-compose']::TEXT[], ARRAY['jetpack-compose', 'compose']::TEXT[]),
  ('tauri', 'Tauri', 'framework', ARRAY[]::TEXT[], ARRAY['tauri', 'tauri-apps']::TEXT[], ARRAY['tauri']::TEXT[]),
  ('electron', 'Electron', 'framework', ARRAY[]::TEXT[], ARRAY['electron', 'electronjs', 'electron-app']::TEXT[], ARRAY['electron']::TEXT[]),
  ('docker', 'Docker', 'platform', ARRAY['Dockerfile']::TEXT[], ARRAY['docker', 'containers', 'containerization', 'docker-compose']::TEXT[], ARRAY['docker', 'dockerfile', 'docker-compose']::TEXT[]),
  ('kubernetes', 'Kubernetes', 'platform', ARRAY[]::TEXT[], ARRAY['kubernetes', 'k8s', 'helm', 'kubectl', 'minikube', 'kind']::TEXT[], ARRAY['kubernetes', 'k8s', 'kubectl', 'helm']::TEXT[]),
  ('aws', 'AWS', 'platform', ARRAY[]::TEXT[], ARRAY['aws', 'amazon-web-services', 'lambda', 's3', 'ec2', 'dynamodb', 'cloudformation', 'cdk', 'sagemaker']::TEXT[], ARRAY['aws', 'amazon', 'lambda', 'cloudformation', 'sagemaker']::TEXT[]),
  ('gcp', 'Google Cloud', 'platform', ARRAY[]::TEXT[], ARRAY['gcp', 'google-cloud', 'firebase', 'bigquery', 'cloud-run', 'cloud-functions']::TEXT[], ARRAY['gcp', 'google-cloud', 'firebase', 'bigquery']::TEXT[]),
  ('azure', 'Azure', 'platform', ARRAY[]::TEXT[], ARRAY['azure', 'microsoft-azure', 'azure-functions', 'azure-devops']::TEXT[], ARRAY['azure']::TEXT[]),
  ('vercel', 'Vercel', 'platform', ARRAY[]::TEXT[], ARRAY['vercel', 'zeit']::TEXT[], ARRAY['vercel']::TEXT[]),
  ('netlify', 'Netlify', 'platform', ARRAY[]::TEXT[], ARRAY['netlify', 'netlify-cms']::TEXT[], ARRAY['netlify']::TEXT[]),
  ('cloudflare', 'Cloudflare', 'platform', ARRAY[]::TEXT[], ARRAY['cloudflare', 'cloudflare-workers', 'cloudflare-pages', 'wrangler']::TEXT[], ARRAY['cloudflare', 'workers']::TEXT[]),
  ('supabase', 'Supabase', 'platform', ARRAY[]::TEXT[], ARRAY['supabase']::TEXT[], ARRAY['supabase']::TEXT[]),
  ('planetscale', 'PlanetScale', 'platform', ARRAY[]::TEXT[], ARRAY['planetscale', 'vitess']::TEXT[], ARRAY['planetscale']::TEXT[]),
  ('digitalocean', 'DigitalOcean', 'platform', ARRAY[]::TEXT[], ARRAY['digitalocean', 'do']::TEXT[], ARRAY['digitalocean']::TEXT[]),
  ('heroku', 'Heroku', 'platform', ARRAY[]::TEXT[], ARRAY['heroku']::TEXT[], ARRAY['heroku']::TEXT[]),
  ('railway', 'Railway', 'platform', ARRAY[]::TEXT[], ARRAY['railway', 'railway-app']::TEXT[], ARRAY['railway']::TEXT[]),
  ('fly', 'Fly.io', 'platform', ARRAY[]::TEXT[], ARRAY['fly', 'flyio', 'fly-io']::TEXT[], ARRAY['fly.io', 'flyctl']::TEXT[]),
  ('terraform', 'Terraform', 'platform', ARRAY['HCL']::TEXT[], ARRAY['terraform', 'infrastructure-as-code', 'iac', 'hashicorp']::TEXT[], ARRAY['terraform', '.tf']::TEXT[]),
  ('pulumi', 'Pulumi', 'platform', ARRAY[]::TEXT[], ARRAY['pulumi', 'infrastructure-as-code']::TEXT[], ARRAY['pulumi']::TEXT[]),
  ('ansible', 'Ansible', 'platform', ARRAY[]::TEXT[], ARRAY['ansible', 'ansible-playbook', 'ansible-role']::TEXT[], ARRAY['ansible']::TEXT[]),
  ('openshift', 'OpenShift', 'platform', ARRAY[]::TEXT[], ARRAY['openshift', 'openshift-container-platform']::TEXT[], ARRAY['openshift']::TEXT[]),
  ('blockchain', 'Blockchain', 'domain', ARRAY['Solidity', 'Vyper', 'Move', 'Cairo']::TEXT[], ARRAY['blockchain', 'distributed-ledger', 'consensus']::TEXT[], ARRAY['blockchain']::TEXT[]),
  ('web3', 'Web3', 'domain', ARRAY[]::TEXT[], ARRAY['web3', 'web3js', 'ethersjs', 'wagmi', 'viem', 'rainbowkit']::TEXT[], ARRAY['web3', 'dapp', 'dapps']::TEXT[]),
  ('ethereum', 'Ethereum', 'domain', ARRAY['Solidity']::TEXT[], ARRAY['ethereum', 'eth', 'evm', 'erc20', 'erc721', 'erc1155', 'eip']::TEXT[], ARRAY['ethereum', 'eth', 'evm']::TEXT[]),
  ('defi', 'DeFi', 'domain', ARRAY[]::TEXT[], ARRAY['defi', 'decentralized-finance', 'dex', 'amm', 'yield-farming', 'liquidity', 'uniswap', 'aave', 'compound']::TEXT[], ARRAY['defi', 'dex', 'amm', 'swap']::TEXT[]),
  ('nft', 'NFT', 'domain', ARRAY[]::TEXT[], ARRAY['nft', 'nfts', 'non-fungible-token', 'erc721', 'erc1155', 'opensea']::TEXT[], ARRAY['nft', 'non-fungible']::TEXT[]),
  ('smart-contracts', 'Smart Contracts', 'domain', ARRAY['Solidity', 'Vyper']::TEXT[], ARRAY['smart-contracts', 'smartcontracts', 'hardhat', 'foundry', 'truffle', 'remix']::TEXT[], ARRAY['smart-contract', 'hardhat', 'foundry']::TEXT[]),
  ('bitcoin', 'Bitcoin', 'domain', ARRAY[]::TEXT[], ARRAY['bitcoin', 'btc', 'lightning-network', 'ordinals', 'brc20']::TEXT[], ARRAY['bitcoin', 'btc', 'lightning']::TEXT[]),
  ('solana', 'Solana', 'domain', ARRAY['Rust']::TEXT[], ARRAY['solana', 'sol', 'anchor', 'solana-program']::TEXT[], ARRAY['solana', 'anchor']::TEXT[]),
  ('polkadot', 'Polkadot', 'domain', ARRAY['Rust']::TEXT[], ARRAY['polkadot', 'substrate', 'parachain', 'kusama']::TEXT[], ARRAY['polkadot', 'substrate']::TEXT[]),
  ('cosmos', 'Cosmos', 'domain', ARRAY['Go']::TEXT[], ARRAY['cosmos', 'cosmos-sdk', 'tendermint', 'ibc']::TEXT[], ARRAY['cosmos', 'tendermint']::TEXT[]),
  ('avalanche', 'Avalanche', 'domain', ARRAY[]::TEXT[], ARRAY['avalanche', 'avax', 'subnet']::TEXT[], ARRAY['avalanche', 'avax']::TEXT[]),
  ('polygon', 'Polygon', 'domain', ARRAY[]::TEXT[], ARRAY['polygon', 'matic', 'polygon-network']::TEXT[], ARRAY['polygon', 'matic']::TEXT[]),
  ('arbitrum', 'Arbitrum', 'domain', ARRAY[]::TEXT[], ARRAY['arbitrum', 'layer2', 'l2']::TEXT[], ARRAY['arbitrum']::TEXT[]),
  ('optimism', 'Optimism', 'domain', ARRAY[]::TEXT[], ARRAY['optimism', 'op-stack', 'layer2']::TEXT[], ARRAY['optimism', 'op-stack']::TEXT[]),
  ('zk', 'Zero Knowledge', 'domain', ARRAY['Circom', 'Cairo']::TEXT[], ARRAY['zero-knowledge', 'zk', 'zkp', 'zk-snark', 'zk-stark', 'zkrollup', 'circom', 'noir']::TEXT[], ARRAY['zero-knowledge', 'zk-snark', 'zk-stark', 'zkrollup']::TEXT[]),
  ('dao', 'DAO', 'domain', ARRAY[]::TEXT[], ARRAY['dao', 'decentralized-autonomous-organization', 'governance', 'aragon', 'snapshot']::TEXT[], ARRAY['dao', 'governance']::TEXT[]),
  ('ai', 'AI / ML', 'domain', ARRAY[]::TEXT[], ARRAY['artificial-intelligence', 'machine-learning', 'deep-learning', 'ai', 'ml']::TEXT[], ARRAY['artificial-intelligence', 'machine-learning', 'deep-learning']::TEXT[]),
  ('llm', 'LLM', 'domain', ARRAY[]::TEXT[], ARRAY['llm', 'large-language-model', 'gpt', 'chatgpt', 'openai', 'claude', 'llama', 'mistral', 'gemini']::TEXT[], ARRAY['llm', 'gpt', 'chatgpt', 'openai', 'langchain', 'llama']::TEXT[]),
  ('agents', 'AI Agents', 'domain', ARRAY[]::TEXT[], ARRAY['ai-agents', 'autonomous-agents', 'agent', 'autogpt', 'langchain', 'crewai', 'autogen']::TEXT[], ARRAY['ai-agent', 'autonomous-agent', 'autogpt', 'crewai']::TEXT[]),
  ('nlp', 'NLP', 'domain', ARRAY[]::TEXT[], ARRAY['nlp', 'natural-language-processing', 'text-mining', 'sentiment-analysis', 'ner', 'transformers']::TEXT[], ARRAY['nlp', 'natural-language']::TEXT[]),
  ('computer-vision', 'Computer Vision', 'domain', ARRAY[]::TEXT[], ARRAY['computer-vision', 'cv', 'image-processing', 'object-detection', 'image-classification', 'yolo', 'opencv']::TEXT[], ARRAY['computer-vision', 'opencv', 'yolo']::TEXT[]),
  ('generative-ai', 'Generative AI', 'domain', ARRAY[]::TEXT[], ARRAY['generative-ai', 'stable-diffusion', 'midjourney', 'dalle', 'diffusion', 'text-to-image', 'image-generation']::TEXT[], ARRAY['generative-ai', 'stable-diffusion', 'diffusion']::TEXT[]),
  ('rag', 'RAG', 'domain', ARRAY[]::TEXT[], ARRAY['rag', 'retrieval-augmented-generation', 'vector-database', 'embeddings', 'semantic-search']::TEXT[], ARRAY['rag', 'retrieval-augmented', 'embeddings']::TEXT[]),
  ('mlops', 'MLOps', 'domain', ARRAY[]::TEXT[], ARRAY['mlops', 'ml-ops', 'mlflow', 'kubeflow', 'model-serving', 'model-deployment']::TEXT[], ARRAY['mlops', 'mlflow', 'kubeflow']::TEXT[]),
  ('tensorflow', 'TensorFlow', 'domain', ARRAY[]::TEXT[], ARRAY['tensorflow', 'tf', 'keras', 'tf-keras']::TEXT[], ARRAY['tensorflow', 'keras']::TEXT[]),
  ('pytorch', 'PyTorch', 'domain', ARRAY[]::TEXT[], ARRAY['pytorch', 'torch', 'torchvision']::TEXT[], ARRAY['pytorch', 'torch']::TEXT[]),
  ('huggingface', 'Hugging Face', 'domain', ARRAY[]::TEXT[], ARRAY['huggingface', 'transformers', 'diffusers', 'datasets']::TEXT[], ARRAY['huggingface', 'hugging-face']::TEXT[]),
  ('langchain', 'LangChain', 'domain', ARRAY[]::TEXT[], ARRAY['langchain', 'langgraph', 'langsmith']::TEXT[], ARRAY['langchain', 'langgraph']::TEXT[]),
  ('security', 'Security', 'domain', ARRAY[]::TEXT[], ARRAY['security', 'cybersecurity', 'infosec', 'appsec', 'application-security']::TEXT[], ARRAY['security', 'cybersecurity']::TEXT[]),
  ('pentesting', 'Pentesting', 'domain', ARRAY[]::TEXT[], ARRAY['penetration-testing', 'pentesting', 'ethical-hacking', 'bug-bounty', 'ctf']::TEXT[], ARRAY['pentesting', 'pentest', 'ethical-hacking']::TEXT[]),
  ('cryptography', 'Cryptography', 'domain', ARRAY[]::TEXT[], ARRAY['cryptography', 'encryption', 'crypto', 'hashing', 'ssl', 'tls']::TEXT[], ARRAY['cryptography', 'encryption']::TEXT[]),
  ('devsecops', 'DevSecOps', 'domain', ARRAY[]::TEXT[], ARRAY['devsecops', 'security-automation', 'sast', 'dast', 'snyk', 'trivy']::TEXT[], ARRAY['devsecops', 'security-automation']::TEXT[]),
  ('devops', 'DevOps', 'domain', ARRAY[]::TEXT[], ARRAY['devops', 'ci-cd', 'continuous-integration', 'continuous-deployment', 'gitops']::TEXT[], ARRAY['devops', 'ci/cd', 'cicd']::TEXT[]),
  ('sre', 'SRE', 'domain', ARRAY[]::TEXT[], ARRAY['sre', 'site-reliability-engineering', 'observability', 'monitoring', 'alerting']::TEXT[], ARRAY['sre', 'site-reliability']::TEXT[]),
  ('platform-engineering', 'Platform Engineering', 'domain', ARRAY[]::TEXT[], ARRAY['platform-engineering', 'internal-developer-platform', 'idp', 'backstage']::TEXT[], ARRAY['platform-engineering', 'backstage']::TEXT[]),
  ('data-engineering', 'Data Engineering', 'domain', ARRAY[]::TEXT[], ARRAY['data-engineering', 'etl', 'data-pipeline', 'data-warehouse', 'data-lake']::TEXT[], ARRAY['data-engineering', 'etl', 'data-pipeline']::TEXT[]),
  ('data-science', 'Data Science', 'domain', ARRAY[]::TEXT[], ARRAY['data-science', 'datascience', 'data-analysis', 'statistics', 'pandas', 'numpy']::TEXT[], ARRAY['data-science', 'datascience']::TEXT[]),
  ('analytics', 'Analytics', 'domain', ARRAY[]::TEXT[], ARRAY['analytics', 'business-intelligence', 'bi', 'data-visualization', 'tableau', 'looker', 'metabase']::TEXT[], ARRAY['analytics', 'business-intelligence']::TEXT[]),
  ('streaming', 'Data Streaming', 'domain', ARRAY[]::TEXT[], ARRAY['kafka', 'apache-kafka', 'streaming', 'stream-processing', 'flink', 'spark-streaming', 'pulsar']::TEXT[], ARRAY['kafka', 'streaming', 'flink']::TEXT[]),
  ('ios', 'iOS', 'domain', ARRAY['Swift', 'Objective-C']::TEXT[], ARRAY['ios', 'ios-app', 'iphone', 'ipad', 'apple', 'uikit', 'swiftui']::TEXT[], ARRAY['ios', 'iphone', 'ipad']::TEXT[]),
  ('android', 'Android', 'domain', ARRAY['Kotlin', 'Java']::TEXT[], ARRAY['android', 'android-app', 'android-development', 'jetpack']::TEXT[], ARRAY['android']::TEXT[]),
  ('mobile', 'Mobile', 'domain', ARRAY[]::TEXT[], ARRAY['mobile', 'mobile-app', 'mobile-development', 'cross-platform']::TEXT[], ARRAY['mobile']::TEXT[]),
  ('gamedev', 'Game Dev', 'domain', ARRAY[]::TEXT[], ARRAY['gamedev', 'game-development', 'game-dev', 'gaming', 'game-engine', 'game']::TEXT[], ARRAY['gamedev', 'game-dev']::TEXT[]),
  ('unity', 'Unity', 'domain', ARRAY['C#']::TEXT[], ARRAY['unity', 'unity3d', 'unity-game-development', 'unityscript']::TEXT[], ARRAY['unity', 'unity3d']::TEXT[]),
  ('unreal', 'Unreal Engine', 'domain', ARRAY['C++']::TEXT[], ARRAY['unreal', 'unreal-engine', 'ue4', 'ue5', 'blueprints']::TEXT[], ARRAY['unreal', 'unreal-engine']::TEXT[]),
  ('godot', 'Godot', 'domain', ARRAY['GDScript']::TEXT[], ARRAY['godot', 'godot-engine', 'gdscript']::TEXT[], ARRAY['godot']::TEXT[]),
  ('frontend', 'Frontend', 'domain', ARRAY[]::TEXT[], ARRAY['frontend', 'front-end', 'ui', 'ux', 'web', 'css', 'html', 'responsive']::TEXT[], ARRAY['frontend', 'front-end']::TEXT[]),
  ('backend', 'Backend', 'domain', ARRAY[]::TEXT[], ARRAY['backend', 'back-end', 'api', 'server', 'rest-api', 'microservices']::TEXT[], ARRAY['backend', 'back-end', 'server']::TEXT[]),
  ('fullstack', 'Full Stack', 'domain', ARRAY[]::TEXT[], ARRAY['fullstack', 'full-stack', 'full-stack-development']::TEXT[], ARRAY['fullstack', 'full-stack']::TEXT[]),
  ('embedded', 'Embedded', 'domain', ARRAY['C', 'C++', 'Rust']::TEXT[], ARRAY['embedded', 'embedded-systems', 'firmware', 'microcontroller', 'rtos', 'arm']::TEXT[], ARRAY['embedded', 'firmware', 'microcontroller']::TEXT[]),
  ('iot', 'IoT', 'domain', ARRAY[]::TEXT[], ARRAY['iot', 'internet-of-things', 'mqtt', 'esp32', 'arduino', 'raspberry-pi', 'home-automation']::TEXT[], ARRAY['iot', 'internet-of-things', 'mqtt']::TEXT[]),
  ('robotics', 'Robotics', 'domain', ARRAY[]::TEXT[], ARRAY['robotics', 'ros', 'ros2', 'robot', 'autonomous', 'slam']::TEXT[], ARRAY['robotics', 'ros', 'robot']::TEXT[]),
  ('ar-vr', 'AR/VR', 'domain', ARRAY[]::TEXT[], ARRAY['ar', 'vr', 'augmented-reality', 'virtual-reality', 'xr', 'mixed-reality', 'metaverse', 'webxr']::TEXT[], ARRAY['augmented-reality', 'virtual-reality', 'ar', 'vr']::TEXT[]),
  ('graphics', '3D Graphics', 'domain', ARRAY['GLSL', 'HLSL']::TEXT[], ARRAY['graphics', '3d', 'opengl', 'vulkan', 'webgl', 'threejs', 'shader', 'rendering']::TEXT[], ARRAY['opengl', 'vulkan', 'webgl', 'threejs']::TEXT[]),
  ('audio', 'Audio', 'domain', ARRAY[]::TEXT[], ARRAY['audio', 'music', 'dsp', 'audio-processing', 'web-audio', 'synthesizer']::TEXT[], ARRAY['audio', 'dsp', 'synthesizer']::TEXT[]),
  ('video', 'Video', 'domain', ARRAY[]::TEXT[], ARRAY['video', 'video-processing', 'ffmpeg', 'streaming', 'video-editing', 'codec']::TEXT[], ARRAY['video', 'ffmpeg', 'codec']::TEXT[]),
  ('cli', 'CLI', 'domain', ARRAY[]::TEXT[], ARRAY['cli', 'command-line', 'terminal', 'shell', 'console']::TEXT[], ARRAY['cli', 'command-line']::TEXT[]),
  ('api-design', 'API Design', 'domain', ARRAY[]::TEXT[], ARRAY['api', 'rest', 'restful', 'openapi', 'swagger', 'api-design', 'grpc']::TEXT[], ARRAY['api', 'rest', 'openapi', 'swagger']::TEXT[]),
  ('testing', 'Testing', 'domain', ARRAY[]::TEXT[], ARRAY['testing', 'unit-testing', 'e2e', 'integration-testing', 'jest', 'cypress', 'playwright', 'pytest']::TEXT[], ARRAY['testing', 'test', 'jest', 'cypress', 'playwright']::TEXT[]),
  ('open-source', 'Open Source', 'domain', ARRAY[]::TEXT[], ARRAY['open-source', 'opensource', 'oss', 'hacktoberfest', 'contributing']::TEXT[], ARRAY['open-source', 'opensource']::TEXT[]),
  ('accessibility', 'Accessibility', 'domain', ARRAY[]::TEXT[], ARRAY['accessibility', 'a11y', 'wcag', 'aria', 'screen-reader']::TEXT[], ARRAY['accessibility', 'a11y']::TEXT[]),
  ('performance', 'Performance', 'domain', ARRAY[]::TEXT[], ARRAY['performance', 'optimization', 'web-performance', 'lighthouse', 'core-web-vitals']::TEXT[], ARRAY['performance', 'optimization']::TEXT[]),
  ('serverless', 'Serverless', 'domain', ARRAY[]::TEXT[], ARRAY['serverless', 'faas', 'lambda', 'cloud-functions', 'serverless-framework']::TEXT[], ARRAY['serverless', 'faas']::TEXT[]),
  ('microservices', 'Microservices', 'domain', ARRAY[]::TEXT[], ARRAY['microservices', 'microservice', 'service-mesh', 'istio', 'linkerd']::TEXT[], ARRAY['microservices', 'microservice']::TEXT[]),
  ('monorepo', 'Monorepo', 'domain', ARRAY[]::TEXT[], ARRAY['monorepo', 'turborepo', 'nx', 'lerna', 'pnpm-workspace']::TEXT[], ARRAY['monorepo', 'turborepo', 'nx']::TEXT[]),
  ('graphql', 'GraphQL', 'tool', ARRAY['GraphQL']::TEXT[], ARRAY['graphql', 'apollo', 'graphql-api', 'hasura', 'relay']::TEXT[], ARRAY['graphql', 'apollo']::TEXT[]),
  ('postgresql', 'PostgreSQL', 'tool', ARRAY[]::TEXT[], ARRAY['postgresql', 'postgres', 'sql', 'psql', 'pg']::TEXT[], ARRAY['postgresql', 'postgres', 'psql']::TEXT[]),
  ('mysql', 'MySQL', 'tool', ARRAY[]::TEXT[], ARRAY['mysql', 'mariadb']::TEXT[], ARRAY['mysql', 'mariadb']::TEXT[]),
  ('mongodb', 'MongoDB', 'tool', ARRAY[]::TEXT[], ARRAY['mongodb', 'mongoose', 'nosql', 'mongo']::TEXT[], ARRAY['mongodb', 'mongoose', 'mongo']::TEXT[]),
  ('redis', 'Redis', 'tool', ARRAY[]::TEXT[], ARRAY['redis', 'caching', 'in-memory']::TEXT[], ARRAY['redis']::TEXT[]),
  ('elasticsearch', 'Elasticsearch', 'tool', ARRAY[]::TEXT[], ARRAY['elasticsearch', 'elastic', 'elk', 'opensearch']::TEXT[], ARRAY['elasticsearch', 'elastic']::TEXT[]),
  ('cassandra', 'Cassandra', 'tool', ARRAY[]::TEXT[], ARRAY['cassandra', 'apache-cassandra', 'scylla']::TEXT[], ARRAY['cassandra', 'scylla']::TEXT[]),
  ('sqlite', 'SQLite', 'tool', ARRAY[]::TEXT[], ARRAY['sqlite', 'sqlite3']::TEXT[], ARRAY['sqlite']::TEXT[]),
  ('dynamodb', 'DynamoDB', 'tool', ARRAY[]::TEXT[], ARRAY['dynamodb', 'dynamo']::TEXT[], ARRAY['dynamodb']::TEXT[]),
  ('neo4j', 'Neo4j', 'tool', ARRAY[]::TEXT[], ARRAY['neo4j', 'graph-database', 'cypher']::TEXT[], ARRAY['neo4j', 'graph-database']::TEXT[]),
  ('clickhouse', 'ClickHouse', 'tool', ARRAY[]::TEXT[], ARRAY['clickhouse', 'olap', 'analytics-database']::TEXT[], ARRAY['clickhouse']::TEXT[]),
  ('drizzle', 'Drizzle', 'tool', ARRAY[]::TEXT[], ARRAY['drizzle', 'drizzle-orm']::TEXT[], ARRAY['drizzle']::TEXT[]),
  ('prisma', 'Prisma', 'tool', ARRAY[]::TEXT[], ARRAY['prisma', 'prisma-orm']::TEXT[], ARRAY['prisma']::TEXT[]),
  ('kafka', 'Kafka', 'tool', ARRAY[]::TEXT[], ARRAY['kafka', 'apache-kafka', 'confluent']::TEXT[], ARRAY['kafka']::TEXT[]),
  ('rabbitmq', 'RabbitMQ', 'tool', ARRAY[]::TEXT[], ARRAY['rabbitmq', 'amqp', 'message-queue']::TEXT[], ARRAY['rabbitmq', 'amqp']::TEXT[]),
  ('nats', 'NATS', 'tool', ARRAY[]::TEXT[], ARRAY['nats', 'nats-io', 'jetstream']::TEXT[], ARRAY['nats']::TEXT[]),
  ('github-actions', 'GitHub Actions', 'tool', ARRAY[]::TEXT[], ARRAY['github-actions', 'github-action', 'actions']::TEXT[], ARRAY['github-actions']::TEXT[]),
  ('gitlab-ci', 'GitLab CI', 'tool', ARRAY[]::TEXT[], ARRAY['gitlab-ci', 'gitlab', 'gitlab-runner']::TEXT[], ARRAY['gitlab-ci', 'gitlab']::TEXT[]),
  ('jenkins', 'Jenkins', 'tool', ARRAY[]::TEXT[], ARRAY['jenkins', 'jenkinsfile', 'jenkins-pipeline']::TEXT[], ARRAY['jenkins']::TEXT[]),
  ('circleci', 'CircleCI', 'tool', ARRAY[]::TEXT[], ARRAY['circleci', 'circle-ci']::TEXT[], ARRAY['circleci']::TEXT[]),
  ('argocd', 'ArgoCD', 'tool', ARRAY[]::TEXT[], ARRAY['argocd', 'argo-cd', 'gitops']::TEXT[], ARRAY['argocd', 'argo-cd']::TEXT[]),
  ('prometheus', 'Prometheus', 'tool', ARRAY[]::TEXT[], ARRAY['prometheus', 'prometheus-monitoring']::TEXT[], ARRAY['prometheus']::TEXT[]),
  ('grafana', 'Grafana', 'tool', ARRAY[]::TEXT[], ARRAY['grafana', 'grafana-dashboard']::TEXT[], ARRAY['grafana']::TEXT[]),
  ('datadog', 'Datadog', 'tool', ARRAY[]::TEXT[], ARRAY['datadog', 'dd']::TEXT[], ARRAY['datadog']::TEXT[]),
  ('opentelemetry', 'OpenTelemetry', 'tool', ARRAY[]::TEXT[], ARRAY['opentelemetry', 'otel', 'tracing', 'observability']::TEXT[], ARRAY['opentelemetry', 'otel']::TEXT[]),
  ('sentry', 'Sentry', 'tool', ARRAY[]::TEXT[], ARRAY['sentry', 'error-tracking']::TEXT[], ARRAY['sentry']::TEXT[]),
  ('spark', 'Apache Spark', 'tool', ARRAY[]::TEXT[], ARRAY['spark', 'apache-spark', 'pyspark']::TEXT[], ARRAY['spark', 'pyspark']::TEXT[]),
  ('airflow', 'Apache Airflow', 'tool', ARRAY[]::TEXT[], ARRAY['airflow', 'apache-airflow', 'dag']::TEXT[], ARRAY['airflow']::TEXT[]),
  ('dbt', 'dbt', 'tool', ARRAY[]::TEXT[], ARRAY['dbt', 'data-build-tool', 'dbt-core']::TEXT[], ARRAY['dbt']::TEXT[]),
  ('flink', 'Apache Flink', 'tool', ARRAY[]::TEXT[], ARRAY['flink', 'apache-flink']::TEXT[], ARRAY['flink']::TEXT[]),
  ('git', 'Git', 'tool', ARRAY[]::TEXT[], ARRAY['git', 'version-control', 'github', 'gitlab', 'bitbucket']::TEXT[], ARRAY['git']::TEXT[]),
  ('nginx', 'Nginx', 'tool', ARRAY[]::TEXT[], ARRAY['nginx', 'reverse-proxy', 'load-balancer']::TEXT[], ARRAY['nginx']::TEXT[]),
  ('vscode', 'VS Code', 'tool', ARRAY[]::TEXT[], ARRAY['vscode', 'visual-studio-code', 'vscode-extension']::TEXT[], ARRAY['vscode', 'visual-studio-code']::TEXT[]),
  ('neovim', 'Neovim', 'tool', ARRAY[]::TEXT[], ARRAY['neovim', 'nvim', 'vim', 'neovim-plugin']::TEXT[], ARRAY['neovim', 'nvim']::TEXT[]),
  ('linux', 'Linux', 'tool', ARRAY[]::TEXT[], ARRAY['linux', 'unix', 'debian', 'ubuntu', 'fedora', 'arch-linux']::TEXT[], ARRAY['linux', 'ubuntu', 'debian']::TEXT[]),
  ('webpack', 'Webpack', 'tool', ARRAY[]::TEXT[], ARRAY['webpack', 'bundler']::TEXT[], ARRAY['webpack']::TEXT[]),
  ('vite', 'Vite', 'tool', ARRAY[]::TEXT[], ARRAY['vite', 'vitejs']::TEXT[], ARRAY['vite']::TEXT[]),
  ('esbuild', 'esbuild', 'tool', ARRAY[]::TEXT[], ARRAY['esbuild']::TEXT[], ARRAY['esbuild']::TEXT[]),
  ('tailwind', 'Tailwind CSS', 'tool', ARRAY[]::TEXT[], ARRAY['tailwindcss', 'tailwind', 'tailwind-css']::TEXT[], ARRAY['tailwind', 'tailwindcss']::TEXT[]),
  ('sass', 'Sass/SCSS', 'tool', ARRAY['SCSS', 'Sass']::TEXT[], ARRAY['sass', 'scss']::TEXT[], ARRAY['sass', 'scss']::TEXT[]),
  ('storybook', 'Storybook', 'tool', ARRAY[]::TEXT[], ARRAY['storybook', 'component-library']::TEXT[], ARRAY['storybook']::TEXT[]),
  ('figma', 'Figma', 'tool', ARRAY[]::TEXT[], ARRAY['figma', 'figma-plugin', 'design-system']::TEXT[], ARRAY['figma']::TEXT[])
ON CONFLICT (slug) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  category = EXCLUDED.category,
  match_languages = EXCLUDED.match_languages,
  match_topics = EXCLUDED.match_topics,
  match_keywords = EXCLUDED.match_keywords;